replicaCount: 4

image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: secretdocker

service:
  name: myservice
  type: NodePort
  port: 80
  targetPort: 8080

secret:
  username: "muruganhub"
  password: "Sures"

