replicaCount: 2

image:
  repository: muruganhub/tasl-prod
  tag: "19"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: secretdocker

service:
  name: myservice
  type: NodePort
  port: 80
  targetPort: 8080

secret:
  username: "muruganhub"
  password: "Sureshraina@3"

